name: Update Clash Rules
on: 
  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci

      - run: mkdir -p Clash/Rules
      - run: node dist/ClashRules.js # Replace 'your-script.js' with the actual path to your JavaScript script
      - uses: actions/upload-artifact@v3
        with:
          name: ClashRules
          path: Clash/Rules
