name: Update Clash Rules
on: 
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - run: mkdir -p Clash/Rules
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v18.17.1  # Adjust the Node.js version if needed

    - name: Install Dependencies
      run: npm install  # You may need to adjust this based on your project's requirements

    - name: Generate YAML Files
      run: node dist/ClashRules.js  # Replace 'your-script.js' with the actual path to your JavaScript script
    - uses: actions/upload-artifact@v3
      with:
        name: ClashRules
        path: Clash/Rules
    
